version: "3.2"
services:
  odc-python-server:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python3 -u run.py
    container_name: odc-python-server
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      mongo_uri: "mongodb://mongodb:27017"
      bind_address: "0.0.0.0"
      bok_location: "./keys/bank_key.pub"
      bpk_location: "./keys/bank_key"
    ports:
      - "80:5000"
    volumes:
      # bpk and bok have to be provided in ./keys as bank_key and bank_key.pub
      - ./keys:/odc/keys
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    logging:
      driver: none
